#
# Copyright Â© 2026 ZTUnion LLC. All rights reserved.
#
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cms.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cms.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tcms.proto\x12\x11willamette.cms.v1\"V\n\x13\x43reateApiKeyRequest\x12\x14\n\x0creal_api_key\x18\x01 \x01(\t\x12)\n\x06policy\x18\x02 \x01(\x0b\x32\x19.willamette.cms.v1.Policy\"/\n\x14\x43reateApiKeyResponse\x12\x17\n\x0fvirtual_api_key\x18\x01 \x01(\t\".\n\x13GetKeyPolicyRequest\x12\x17\n\x0fvirtual_api_key\x18\x01 \x01(\t\"\x7f\n\x14GetKeyPolicyResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x17\n\x0fvirtual_api_key\x18\x02 \x01(\t\x12\x14\n\x0creal_api_key\x18\x03 \x01(\t\x12)\n\x06policy\x18\x04 \x01(\x0b\x32\x19.willamette.cms.v1.Policy\"/\n\x14ResolveApiKeyRequest\x12\x17\n\x0fvirtual_api_key\x18\x01 \x01(\t\"\x80\x01\n\x15ResolveApiKeyResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x17\n\x0fvirtual_api_key\x18\x02 \x01(\t\x12\x14\n\x0creal_api_key\x18\x03 \x01(\t\x12)\n\x06policy\x18\x04 \x01(\x0b\x32\x19.willamette.cms.v1.Policy\"\x15\n\x13ListPoliciesRequest\"N\n\x14ListPoliciesResponse\x12\x36\n\x05items\x18\x01 \x03(\x0b\x32\'.willamette.cms.v1.GetKeyPolicyResponse\"\xeb\x01\n\x06Policy\x12\x1d\n\x15ip_validation_enabled\x18\x01 \x01(\x08\x12\x19\n\x11\x61llowed_ip_ranges\x18\x02 \x03(\t\x12\x1e\n\x16ja3_validation_enabled\x18\x03 \x01(\x08\x12\x13\n\x0b\x61llowed_ja3\x18\x04 \x03(\t\x12\x1e\n\x16ja4_validation_enabled\x18\x05 \x01(\x08\x12\x13\n\x0b\x61llowed_ja4\x18\x06 \x03(\t\x12\"\n\x1a\x63ountry_validation_enabled\x18\x07 \x01(\x08\x12\x19\n\x11\x61llowed_countries\x18\x08 \x03(\t2\x93\x03\n\nCmsService\x12_\n\x0c\x43reateApiKey\x12&.willamette.cms.v1.CreateApiKeyRequest\x1a\'.willamette.cms.v1.CreateApiKeyResponse\x12_\n\x0cGetKeyPolicy\x12&.willamette.cms.v1.GetKeyPolicyRequest\x1a\'.willamette.cms.v1.GetKeyPolicyResponse\x12\x62\n\rResolveApiKey\x12\'.willamette.cms.v1.ResolveApiKeyRequest\x1a(.willamette.cms.v1.ResolveApiKeyResponse\x12_\n\x0cListPolicies\x12&.willamette.cms.v1.ListPoliciesRequest\x1a\'.willamette.cms.v1.ListPoliciesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cms_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEAPIKEYREQUEST']._serialized_start=32
  _globals['_CREATEAPIKEYREQUEST']._serialized_end=118
  _globals['_CREATEAPIKEYRESPONSE']._serialized_start=120
  _globals['_CREATEAPIKEYRESPONSE']._serialized_end=167
  _globals['_GETKEYPOLICYREQUEST']._serialized_start=169
  _globals['_GETKEYPOLICYREQUEST']._serialized_end=215
  _globals['_GETKEYPOLICYRESPONSE']._serialized_start=217
  _globals['_GETKEYPOLICYRESPONSE']._serialized_end=344
  _globals['_RESOLVEAPIKEYREQUEST']._serialized_start=346
  _globals['_RESOLVEAPIKEYREQUEST']._serialized_end=393
  _globals['_RESOLVEAPIKEYRESPONSE']._serialized_start=396
  _globals['_RESOLVEAPIKEYRESPONSE']._serialized_end=524
  _globals['_LISTPOLICIESREQUEST']._serialized_start=526
  _globals['_LISTPOLICIESREQUEST']._serialized_end=547
  _globals['_LISTPOLICIESRESPONSE']._serialized_start=549
  _globals['_LISTPOLICIESRESPONSE']._serialized_end=627
  _globals['_POLICY']._serialized_start=630
  _globals['_POLICY']._serialized_end=865
  _globals['_CMSSERVICE']._serialized_start=868
  _globals['_CMSSERVICE']._serialized_end=1271
# @@protoc_insertion_point(module_scope)
