#
# Copyright Â© 2026 ZTUnion LLC. All rights reserved.
#
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cms_pb2 as cms__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cms_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CmsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateApiKey = channel.unary_unary(
                '/willamette.cms.v1.CmsService/CreateApiKey',
                request_serializer=cms__pb2.CreateApiKeyRequest.SerializeToString,
                response_deserializer=cms__pb2.CreateApiKeyResponse.FromString,
                _registered_method=True)
        self.GetKeyPolicy = channel.unary_unary(
                '/willamette.cms.v1.CmsService/GetKeyPolicy',
                request_serializer=cms__pb2.GetKeyPolicyRequest.SerializeToString,
                response_deserializer=cms__pb2.GetKeyPolicyResponse.FromString,
                _registered_method=True)
        self.ResolveApiKey = channel.unary_unary(
                '/willamette.cms.v1.CmsService/ResolveApiKey',
                request_serializer=cms__pb2.ResolveApiKeyRequest.SerializeToString,
                response_deserializer=cms__pb2.ResolveApiKeyResponse.FromString,
                _registered_method=True)
        self.ListPolicies = channel.unary_unary(
                '/willamette.cms.v1.CmsService/ListPolicies',
                request_serializer=cms__pb2.ListPoliciesRequest.SerializeToString,
                response_deserializer=cms__pb2.ListPoliciesResponse.FromString,
                _registered_method=True)


class CmsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateApiKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKeyPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveApiKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPolicies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CmsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateApiKey,
                    request_deserializer=cms__pb2.CreateApiKeyRequest.FromString,
                    response_serializer=cms__pb2.CreateApiKeyResponse.SerializeToString,
            ),
            'GetKeyPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKeyPolicy,
                    request_deserializer=cms__pb2.GetKeyPolicyRequest.FromString,
                    response_serializer=cms__pb2.GetKeyPolicyResponse.SerializeToString,
            ),
            'ResolveApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveApiKey,
                    request_deserializer=cms__pb2.ResolveApiKeyRequest.FromString,
                    response_serializer=cms__pb2.ResolveApiKeyResponse.SerializeToString,
            ),
            'ListPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPolicies,
                    request_deserializer=cms__pb2.ListPoliciesRequest.FromString,
                    response_serializer=cms__pb2.ListPoliciesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'willamette.cms.v1.CmsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('willamette.cms.v1.CmsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CmsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/willamette.cms.v1.CmsService/CreateApiKey',
            cms__pb2.CreateApiKeyRequest.SerializeToString,
            cms__pb2.CreateApiKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKeyPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/willamette.cms.v1.CmsService/GetKeyPolicy',
            cms__pb2.GetKeyPolicyRequest.SerializeToString,
            cms__pb2.GetKeyPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/willamette.cms.v1.CmsService/ResolveApiKey',
            cms__pb2.ResolveApiKeyRequest.SerializeToString,
            cms__pb2.ResolveApiKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/willamette.cms.v1.CmsService/ListPolicies',
            cms__pb2.ListPoliciesRequest.SerializeToString,
            cms__pb2.ListPoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
